myapp/urls.py
from django.urls import path
from . import views

app_name = 'myapp'

urlpatterns = [
    path('home/', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('skill/', views.skill, name='skill'),
    path('contact/', views.contact, name='contact'),
    # path('download-pdf/', views.download_pdf, name='download_pdf'),
    path('download-pdf/', views.my_view, name='download_pdf'),
    
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', views.home, name='default'),
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/models.py
from django.db import models

# Create your models here.
# name =  models.Model.models.CharField(_(""), max_length=50)
class Contact(models.Model):
    name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.CharField(max_length=1000)


    def __str__(self):
        return 'I got Your Message {self.name}'

myapp/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta :
        model = Contact
        fields = ['name', 'email', 'message']

myapp/views.py
from django.shortcuts import render
from django.contrib.staticfiles.storage import staticfiles_storage
from.forms import ContactForm
from django.core.mail import send_mail
from django.http import HttpResponse, FileResponse
from django.conf import settings
from wsgiref.util import FileWrapper
import re
import os


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        
        if form.is_valid():
            form.save()
            name = form.cleaned_data['name']
            email = form.cleaned_data['email']
            message = form.cleaned_data['message']

            recipients = ['vikiadhi2016@gmail.com']
            if message:
                sender = ''
            send_mail(recipient_list=recipients, subject=f'New Mail from Your Portfolio Website!😀. Sender {email}', message=f'Hi vikram my name is, {name}\r\n \r\n Message:{message}', from_email='shieldgamer9444@gmail.com')

            return render(request, 'response.html')
    else:
        form = ContactForm()
    return render(request, 'contact.html', {'form': form})



# Create your views here.
def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def skill(request):
    return render(request, 'skill.html')

# def navbar(request):
#     return render(request, 'navbar.html')

# def download_pdf(request):
#     with open('myapp/static/cv.pdf', 'rb') as f:
#         response = FileResponse(f, as_attachment=True, filename='cv.pdf')
#     return response


def download_pdf(request, filename):
    file_path = os.path.join('myapp', 'static', filename)
    file = open(file_path, 'rb')
    file_name = os.path.basename(file_path)
    response = HttpResponse(FileWrapper(file), content_type='application/octet-stream')
    response['Content-Disposition'] = f'attachment; filename="{file_name}"'
    return response


def my_view(request):
    # Get the file name from the user somehow
    file_name = 'cv.pdf'
    response = download_pdf(request, file_name)
    return response

myapp/templates/about.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>About</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'about.css' %}">
    <!-- <script src="main.js"></script> -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@700&family=Open+Sans&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <div class="navbar">
            <div class="logo  hvr-underline-from-center"><h2 class="heading">About</h2></div>
            <ul class="links  ">
                <li class="hvr-float-shadow"><a href="{% url 'myapp:home' %}">Home</a></li>
                <li class="hvr-float-shadow"><a href="{% url 'myapp:about' %}">About</a></li>
                <li class="hvr-float-shadow"><a href="{% url 'myapp:skill' %}">Skills</a></li>
                <li class="hvr-float-shadow"><a href="{% url 'myapp:contact'%}">Contact</a></li>
            </ul>
            <!-- <a href="#" class="action_btn">Get Started</a> -->
            <div class="toggle_btn">
                <i class="fa-solid fa-bars"></i>
            </div>
        </div>
        <div class="content1">
            <ul>
                <h2 class="name ">Personal Details</h2><br>
        
                <li><p class="edu">Full name: Vikraman Mathivanan</p></li>
                <li><p class="edu">Date of Birth: 30/03/2002</p></li>
                <li><p class="edu">Phone: +91 9514531375</p></li>
                <li><p class="edu">City: Villupuram, India</p></li>
                <li><p class="edu">Email: <a href="#">vikiadhi2016@gmail.com</a></p></li><br> 

                <h2 class="name">Education</h2> <br>
                <li><p class="edu">DIPLOMA IN HEALTH INSPECTOR</p></li>
                <li><p class="year edu">2019 - 2022</p></li>
                <li><p class="edu"> HSC - BIOLOGY & MATHEMATICS</p></li>
                <li><p class="year edu">2018 - 2019</p></li>
                <li><p class="edu">SSLC - GENERAL</p></li>
                <li><p class="year edu">2016 - 2017</p></li>
            </ul>
   
           
        </div> 

        <div class="projects">
            <ul>
                <h2 class="name">Projects</h2><br>
                <li><p class="top"><span><i class="fa-solid fa-arrow-right arrow"></i></span> Amazon product alert project with web Scraping(Selenium).</p></li><br>
                <li><p class="bot"><span><i class="fa-solid fa-arrow-right arrow"></i></span> Worked in Data analysis projects with Pandas, Matplotlib.</p></li><br>
                <li><p class="top"><i class="fa-solid fa-arrow-right arrow arrow"></i></span> Personal portfolio site with CSS, HTML, Bootstrap. </p></li><br>
                <li><p class="bot"><i class="fa-solid fa-arrow-right arrow"></i></span> Blog Post Website using Flask, WTF Forms.</p></li><br>
                <li><p class="top"><i class="fa-solid fa-arrow-right arrow"></i></span> Familiar with API's and creating RESTFUL API.</p></li><br>
                <li><p class="bot"><i class="fa-solid fa-arrow-right arrow"></i></span> Games : Tic Tac Toe , Snake Game, Hang Man etc.</p></li><br>
                <li><p class="top"><i class="fa-solid fa-arrow-right arrow"></i></span> And This Portfolio Website was built with Django.</p></li>
            </ul>
        </div>



        <div class="dropdown_menu">
            <ul class="links">
                <li><a href="{% url 'myapp:home' %}">Home</a></li>
                <li><a href="{% url 'myapp:about' %}">About</a></li>
                <li><a href="{% url 'myapp:skill' %}">Skills</a></li>
                <li><a href="{% url 'myapp:contact' %}">Contact</a></li>
                <!-- <li><a href="#" class="action_btn">Get Started</a></li> -->
            </ul>  
            <button class="net-btn1  hvr-radial-out"><a href="https://www.linkedin.com/in/vikraman-m-4067b5252"></a><i class="fa-brands fa-linkedin"></i></button>          
            <button class="net-btn2  hvr-radial-out"><a href="https://www.instagram.com/romanviki_nbd/"></a><i class="fa-brands fa-instagram"></i></i></button>
            <button class="net-btn3  hvr-radial-out"><a href="https://github.com/ROMANVIKI"></a><i class="fa-brands fa-github"></i></button>          
        </div>
        
    
    </header>
    <script>
        const toggleBtn = document.querySelector('.toggle_btn')
        const toggleBtnIcon = document.querySelector('.toggle_btn i')
        const dropDownMenu = document.querySelector('.dropdown_menu')

        toggleBtn.onclick = function () {
            dropDownMenu.classList.toggle('open')
        }
    </script>
</body>
</html>

myapp/templates/contact.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1"> 
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Contact</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'contact.css' %}">
    
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@700&family=Open+Sans&display=swap" rel="stylesheet">
    <style>
        body {
            background-image: url("{% static 'mn.jpg' %}");
        }
    </style>
</head>
<body>
    <header>
        <div class="navbar">
            <div class="logo  hvr-underline-from-center"><h2 class="heading">Contact</h2></div>
            <ul class="links  ">
                <li class="hvr-float-shadow"><a href="{% url 'myapp:home' %}">Home</a></li>
                <li class="hvr-float-shadow"><a href="{% url 'myapp:about' %}">About</a></li>
                <li class="hvr-float-shadow"><a href="{% url 'myapp:skill' %}">Skills</a></li>
                <li class="hvr-float-shadow"><a href="{% url 'myapp:contact' %}">Contact</a></li>
            </ul>
            <!-- <a href="#" class="action_btn">Get Started</a> -->
            <div class="toggle_btn">
                <i class="fa-solid fa-bars"></i>
            </div>
        </div>
        <div class="contact-box">
            <h2>Text Me!</h2>
            <form method="post" action="">
                {% csrf_token %}
                
                <div class="user-box">
                    <!-- {{ form.as_p }} -->
                    {{ form.name }}
                    <!-- <input type="text" name="" required> -->
                     <label for="">Name</label>
                </div>
                <div class="user-box">
                    {{ form.email }} 
                    <!-- <input type="email" name="" required> -->
                    <label for="">Your Email</label>
                </div>
                <div class="user-box">
                    {{ form.message }}
                    <!-- <input type="text" name="" required> -->
                    <label for="">Your Message</label>
                </div>
                <button class="cybr-btn">
                    <button class="custom-btn btn-6"><span>Submit</span></button>
                </button>
            </form>

        </div>

        <div class="dropdown_menu">
            <ul class="links">
                <li><a href="{% url 'myapp:home' %}">Home</a></li>
                <li><a href="{% url 'myapp:about' %}">About</a></li>
                <li><a href="{% url 'myapp:skill' %}">Skills</a></li>
                <li><a href="{% url 'myapp:contact' %}">Contact</a></li>
                <!-- <li><a href="#" class="action_btn">Get Started</a></li> -->
            </ul>  
            <button class="net-btn1  hvr-radial-out"><a href="https://www.linkedin.com/in/vikraman-m-4067b5252"></a><i class="fa-brands fa-linkedin"></i></button>          
            <button class="net-btn2  hvr-radial-out"><a href="https://www.instagram.com/romanviki_nbd/"></a><i class="fa-brands fa-instagram"></i></i></button>
            <button class="net-btn3  hvr-radial-out"><a href="https://github.com/ROMANVIKI"></a><i class="fa-brands fa-github"></i></button>          
        </div>
        
    
    </header>
    <script>
        const toggleBtn = document.querySelector('.toggle_btn')
        const toggleBtnIcon = document.querySelector('.toggle_btn i')
        const dropDownMenu = document.querySelector('.dropdown_menu')

        toggleBtn.onclick = function () {
            dropDownMenu.classList.toggle('open')
        }
    </script>
</body>

</html>

myapp/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Vikram's Portfolio Website</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">
</head>
<body>
    <header class="header">
        <a href="{% url 'myapp:home' %}" class="logo hvr-underline-from-center">Portfolio</a>
        <div>
            <nav class="navbar">
                <a href="{% url 'myapp:home' %}" style="--i:1;" class="active hvr-float-shadow">Home</a>
                <a href="{% url 'myapp:about' %}" style="--i:2;" class="hvr-float-shadow">About</a>
                <a href="{% url 'myapp:skill' %}" style="--i:3;" class="hvr-float-shadow">Skills</a>
                <a href="{% url 'myapp:contact' %}" style="--i:4;" class="hvr-float-shadow">Contact</a>
                
            </nav>
        </div>
        <div class="menu0">
            <input type="checkbox" id="check0">
            <label for="check0" class="button0">
                <span></span>
                <span></span>
                <span></span>
            </label>
            <nav class='nav0'>
                <a href="{% url 'myapp:about' %}">About</a>
                <a href="{% url 'myapp:skill' %}">Skills</a>
                <a href="{% url 'myapp:contact' %}">Contact</a>
            </nav>
        </div>

    </header>
  
    

    <section class="home">
        <div class="home-content">
            
            <h3>Hello, It's Me</h3>
            <h1>Vikraman</h1>
            <h3>& I'm a <span class="multiple-text"></span></h3>
            
            <div class="social-media">
                <a href="https://www.linkedin.com/in/vikraman-m-4067b5252" style="--i:7;"><i class='bx bxl-linkedin'></i></a>
                <a href="https://www.instagram.com/romanviki_nbd/" style="--i:8;"><i class='bx bxl-instagram-alt'></i></a>
                <a href="https://github.com/ROMANVIKI" style="--i:9;"><i class='bx bxl-github' ></i></a>
                <a href="https://discord.gg/nN4kgQAa" style="--i:10;"><i class='bx bxl-discord-alt' ></i></a>
            </div>
            <a href="{% url 'myapp:download_pdf' %}" class="btn">Download CV</a>
        </div>
        <div class="home-img">
            <img src="{% static 'pic(2).png' %}" alt="">
        </div>
    </section>
    
    <script src="https://cdn.jsdelivr.net/npm/typed.js@2.0.12"></script>
    <script src="{% static 'script.js' %}"></script>
</body>
</html>

myapp/templates/response.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Response</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'response.css' %}">
    <style>
        body {
            background-image: url("{% static 'response-img.jpg' %}");
        }
    </style>
</head>
<body>

    <div class="response">
        
        <h2>Thank You for the Response😀. </h2><br>
        <h3>Click the home button to redirect to the home page.</h3>  

    </div><br> <br>
    <div>
        <a href="{% url 'myapp:home' %}">
            <button class="cybr-btn">
                HOME<span aria-hidden>_</span>
                <span aria-hidden class="cybr-btn__glitch">ROMANVIKI_</span>
                <span aria-hidden class="cybr-btn__tag">RV</span>
            </button>
        </a>
    </div>
    
</body>
</html>

myapp/templates/skill.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>Skills</title>
    <link rel="shortcut icon" type="image/x-icon" href="{% static 'favicon.ico' %}">

    <link rel="stylesheet" href="{% static 'skill.css' %}">
    <!-- <script src="skil.js"></script> -->
    <style>
        body {
            background-image: url("{% static 'astronaut.jpg' %}");
        }
    </style>
</head>
<body>
    <header>
        <div class="navbar">
            <div class="topic hvr-underline-from-center"><a href="#">Skills</a></div>
            <ul class="link">
                <li><a href="{% url 'myapp:home' %}" class="hvr-float-shadow home-link">Home</a></li>
                <li><a href="{% url 'myapp:about' %}" class="hvr-float-shadow about-link">About</a></li>
                <li><a href="{% url 'myapp:skill' %}" class="hvr-float-shadow skills-link">Skills</a></li>
                <li><a href="{% url 'myapp:contact' %}" class="hvr-float-shadow contact-link">Contact</a></li>
            </ul>
        </div>
        
    </header>
    <script>
        const toggleButton = document.querySelector('.toggle-button')
        const toggleButtonIcon = document.querySelector('.toggle-button i')
        const dropDownMenu = document.querySelector('.dropdown-menu')


        toggleButton.onclick = function() {
            dropDownMenu.classList.toggle('open')
        }
    </script>



    <div class="skills">  
        
        <li>
            <h3>Python</h3><span class="bar"><span class="html"></span></span> 
        </li>
    
        <li>
            <h3>HTML</h3><span class="bar"><span class="css"></span></span>
        </li>
    
        <li>
            <h3>CSS</h3><span class="bar"><span class="javascript"></span></span>
        </li>
    
        <li>
            <h3>Django, Flask</h3><span class="bar"><span class="jquery"></span></span>
        </li>
    </div>
</body>
</html>